import json

states = [ "AK","AL",
                      "AR",
                      "AS",
                      "AZ",
                      "CA",
                      "CO",
                      "CT",
                      "DC",
                      "DE",
                      "FL",
                      "GA",
                      "GU",
                      "HI",
                      "IA",
                      "ID",
                      "IL",
                      "IN",
                      "KS",
                      "KY",
                      "LA",
                      "MA",
                      "MD",
                      "ME",
                      "MI",
                      "MN",
                      "MO",
                      "MS",
                      "MT",
                      "NC",
                      "ND",
                      "NE",
                      "NH",
                      "NJ",
                      "NM",
                      "NV",
                      "NY",
                      "OH",
                      "OK",
                      "OR",
                      "PA",
                      "PR",
                      "RI",
                      "SC",
                      "SD",
                      "TN",
                      "TX",
                      "UT",
                      "VA",
                      "VI",
                      "VT",
                      "WA",
                      "WI",
                      "WV",
                      "WY"]
statedict = {
"AK" : "Alaska",
"AL" : "Alabama",
"AR" : "Arkansas",
"AS" : "American Samoa",
"AZ" : "Arizona",
"CA" : "California",
"CO" : "Colorado",
"CT" : "Connecticut",
"DC" : "District of Columbia",
"DE" : "Delaware",
"FL" : "Florida",
"GA" : "Georgia",
"GU" : "Guam",
"HI" : "Hawaii",
"IA" : "Iowa",
"ID" : "Idaho",
"IL" : "Illinois",
"IN" : "Indiana",
"KS" : "Kansas",
"KY" : "Kentucky",
"LA" : "Louisiana",
"MA" : "Massachusetts",
"MD" : "Maryland",
"ME" : "Maine",
"MI" : "Michigan",
"MN" : "Minnesota",
"MO" : "Missouri",
"MS" : "Mississippi",
"MT" : "Montana",
"NC" : "North Carolina",
"ND" : " North Dakota",
"NE" : "Nebraska",
"NH" : "New Hampshire",
"NJ" : "New Jersey",
"NM" : "New Mexico",
"NV" : "Nevada",
"NY" : "New York",
"OH" : "Ohio",
"OK" : "Oklahoma",
"OR" : "Oregon",
"PA" : "Pennsylvania",
"PR" : "Puerto Rico",
"RI" : "Rhode Island",
"SC" : "South Carolina",
"SD" : "South Dakota",
"TN" : "Tennessee",
"TX" : "Texas",
"UT" : "Utah",
"VA" : "Virginia",
"VI" : "Virgin Islands",
"VT" : "Vermont",
"WA" : "Washington",
"WI" : "Wisconsin",
"WV" : "West Virginia",
"WY" : "Wyoming"
}
APIKEY = "b92ebadc830c4cc5a4cf1ff6c26cb222"
data = {"intents": []}
for s in states:
    url = "https://api.covidactnow.org/v2/state/%s.json?apiKey=%s" %(s, APIKEY)
    pat = [
        "New cases in %s" %(statedict[s]),
        "Show me covid cases in %s" %(statedict[s]),
        "Covid data in %s" %(statedict[s]),
    ]
    d = {
        "tag": "covid_cases_%s" %(s),
        "patterns": pat,
        "responses": [url]
    }
    data["intents"].append(d)

with open('test.json', 'w') as f:
    json.dump(data, f)